# These are supported funding model platforms
gitHub: []  # No GitHub Sponsors username provided
patreon: arvindranga69
buy_me_a_coffee: arvindrangv
custom: [https://paypal.me/arvindranga69, upi://pay?pa=arvindranga69@okhdfcbank&pn=ArvindRanga]
